### ISSUE TITLE
What is origin and trustedOrigins?

### ISSUE THREAD

**Issue by pheyvaer** [solid/acl-check#10]
Both `origin` and  `trustedOrigins` are mentioned in the usage section in the README. What is this?

**Comment by kjetilk** [comment]
`origin` is the actual origin you get from the browser, `trustedOrigins` is an array of origins that you can trust to not give you malicious code. Typically, the latter will be configured on the server and passed from there to the checker.

**Comment by pheyvaer** [comment]
I see. Would origin be `https://alice.example.com/` in your example then?

**Comment by megoth** [comment]
I reckon this issue is solved, and am closing it (let me know if you want it opened).
