### ISSUE TITLE
Public resources should be available to all origins

### ISSUE THREAD

**Issue by angelo-v** [solid/acl-check#15]
**Expected behaviour**:

A GET request to a resource, that is publically readable (e.g. a Solid WebID profile) should succeed with 200 OK from any orgin.

**Actual behavour**:

A GET request to such a resource is responed with 403 Forbidden when an origin header is set.

**Example to reproduce**:

ACL for https://angelo.veltens.org/profile:
```
# The public has read permissions
<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;
    acl:accessTo <./>;
    acl:defaultForNew <./>;
    acl:mode acl:Read.
```
curl with origin:
```
▶ curl -I -H Origin:https://markbook.org https://angelo.veltens.org/profile/card
HTTP/2 403
```
curl without origin:
```
▶ curl -I https://angelo.veltens.org/profile/card                               
HTTP/2 200
```

**From the spec**:

> [...] This is the algorithm the server must go through.
> * If the requested mode is available to the public, then succeed 200 OK [...] 

Source: https://github.com/solid/web-access-control-spec#referring-to-origins-ie-web-apps

**Comment by kjetilk** [comment]
Thanks a lot! I can confirm it is a bug, and I have a plan to fix it.
